### ISSUE TITLE
Mouse wheel zoom in

### ISSUE THREAD

**Issue by ggonnella** [niehus/gfaviz#1]
Zoom in the graph pane works with:
- buttons on the bottom
- CTRL +/-

However, it would be nice to have it working with the mouse wheel.
In Bandage it does -> TODO: check how.

Maybe this helps too:
https://wiki.qt.io/Smooth_Zoom_In_QGraphicsView

**Comment by holtsetio** [comment]
Added in 731af1ddda197dfe73c5139653852b047f2467fe. Press CTRL to zoom with mousewheel.
