### ISSUE TITLE
Position of fragments of previously moved segments after redrawing

### ISSUE THREAD

**Issue by ggonnella** [niehus/gfaviz#11]
If one moves a segment containing a fragment manually, then redraws (using "Apply layout!"), the fragment remains at the previous position relative the previous segment position, i.e. it's "lost in space".

![screenshot_20180828_120235](https://user-images.githubusercontent.com/21620/44716328-46026080-aaba-11e8-81fe-9431ad238e62.png)

**Comment by holtsetio** [comment]
Fixed in 731af1ddda197dfe73c5139653852b047f2467fe.

**Comment by ggonnella** [comment]
I still have this bug, will show you tomorrow.

**Comment by ggonnella** [comment]
The bug is fixed.
