### ISSUE TITLE
PNG exported image has transparent background

### ISSUE THREAD

**Issue by ggonnella** [niehus/gfaviz#15]
Output to PNG produced for me an unusable image.
The problem lies in the background.

Example:
![screenshot_20180829_115534](https://user-images.githubusercontent.com/21620/44780550-79102700-ab82-11e8-993b-6100225c054c.png)

should be:
![screenshot_20180829_115642](https://user-images.githubusercontent.com/21620/44780616-a230b780-ab82-11e8-82b2-16f5634aabe2.png)

**Comment by ggonnella** [comment]
The problem seems to be actually related to the visualization software.
I.e. when attaching the png here, there is problem:

![graph gfa](https://user-images.githubusercontent.com/21620/44785286-ab288580-ab90-11e8-9869-0b2749cd085e.png)

(This was generated using ''./viz.x -n testdata/graph.gfa -r'')

**Comment by ggonnella** [comment]
Opening the file with Gimp, the "problem" becomes clear. There is no background. 

![screenshot_20180829_133936](https://user-images.githubusercontent.com/21620/44785428-22f6b000-ab91-11e8-8cd0-69ea4b923eea.png)

Now the bug becomes a minor annoyance. Should we add a white background? I think that would be better.

**Comment by holtsetio** [comment]
Modified in 731af1ddda197dfe73c5139653852b047f2467fe. The transparent background is now optional (--transparency command line option and option in the export dialog).
