### ISSUE TITLE
SVG export issue (from GUI)

### ISSUE THREAD

**Issue by ggonnella** [niehus/gfaviz#16]
When exporting to SVG (after installing the required dev library and re-compiling), nothing was actually exported, i.e. no file is created.

**Comment by ggonnella** [comment]
Using the command line the export is working:

```
./viz.x -n testdata/graph.gfa -r -f SVG
```

created a file gfaph.gfa.SVG (minor annoyance: I think the extension SVG should be rather with lowecase letters)

**Comment by holtsetio** [comment]
Could not reproduce. Also the case of the extensions depends on the command line argument used. "-f sVg" produces "graph.gfa.sVg".

**Comment by ggonnella** [comment]
I cannot reproduce it either anymore. Close for now.
