### ISSUE TITLE
Negative paths length

### ISSUE THREAD

**Issue by ggonnella** [niehus/gfaviz#20]
The specification allows for negative gaps and Abyss2 emits negative gaps in scaffolding graphs. Negative gaps are approximate overlaps of contigs.

The following patch solves the problem:
[patch_gaps.txt](https://github.com/niehus/gfaviz/files/2346212/patch_gaps.txt)

(apply using ``git apply patch_gaps.txt``)

**Comment by holtsetio** [comment]
Patch applied in 9c0ac9b42718a07638186ca76b306afab55dddc3
