### ISSUE TITLE
Default color of segments too dark

### ISSUE THREAD

**Issue by ggonnella** [niehus/gfaviz#21]
The color of segments is by default 100% blue (#0000ff) but this does not allow to see the labels. The default color should be changed to a light color.

The following patch changes the default color to a light color:
[seg_color_patch.txt](https://github.com/niehus/gfaviz/files/2346216/seg_color_patch.txt)

**Comment by holtsetio** [comment]
Patch applied in 9c0ac9b42718a07638186ca76b306afab55dddc3. Not so sure about the color yet.
