### ISSUE TITLE
Node length

### ISSUE THREAD

**Issue by ggonnella** [niehus/gfaviz#23]
I would change some of the weights of the node lengths. The problem is for me that the difference between short and long nodes is too less.

In particular, I experimented with changed to 10 the multiplication factor 2 in ``viznode.cpp`` ``vg->GA.doubleWeight(e)``. This makes all nodes 5 times longer and I like the result.

Also I would change the default minimum weight to 1 (instead of 12) in ``vizsetting.cpp``.

**Comment by holtsetio** [comment]
Modified node lengths a bit in 9c0ac9b42718a07638186ca76b306afab55dddc3, not as much as suggested though. Also changed how shorter nodes are handled. Final default values have yet to be decided on.

**Comment by ggonnella** [comment]
I will make the weight parametric.
