### ISSUE TITLE
Set colors of edges (and evtl linestyle) and gaps from GUI

### ISSUE THREAD

**Issue by ggonnella** [niehus/gfaviz#25]
The color of edges and gaps cannot be set from the GUI. This should be fixed.

**Comment by holtsetio** [comment]
Added some options in 9c0ac9b42718a07638186ca76b306afab55dddc3. Linestyle can not yet be modified, and the group color option still needs work when applied to several groups (Allow selection of a color scheme instead of a single color).

**Comment by ggonnella** [comment]
I think this is enough. The linestyle is not a big problem. The group color is treaky, but we should open another issue for that.
