### ISSUE TITLE
Selection highlight

### ISSUE THREAD

**Issue by ggonnella** [niehus/gfaviz#27]
Sometimes it is very difficult to find the selection visually. E.g. when a small segment is searched, then it is selected, but cannot be spotted easily.

Currently the selection is highlighted only by a rectangle box. I think another kind of highlighting of the selection would be more appropriate (e.g. darken colors).

**Comment by holtsetio** [comment]
Fixed in 9c0ac9b42718a07638186ca76b306afab55dddc3
