### ISSUE TITLE
Fragment drawing shall be a short line and not a circle

### ISSUE THREAD

**Issue by ggonnella** [niehus/gfaviz#28]
Fragments are currently represented as a circle ``path.addEllipse(p2, 2, 2)`` in ``vizFragment::draw()`` in ``vizfragment.cpp``. This shall be changed, as an ellipse is a bad representation for a fragment of sequence.

We should change this into a short line.

**Comment by holtsetio** [comment]
Fixed in 9c0ac9b42718a07638186ca76b306afab55dddc3. Can still be improved I guess.

**Comment by ggonnella** [comment]
Much better now.

Could we use the length of the alignment to choose the length of the line (and use the current value as minimum)? This would be similar to what done with the segments (maybe even using the same equation).
