### ISSUE TITLE
Performance when many elements are selected

### ISSUE THREAD

**Issue by holtsetio** [niehus/gfaviz#37]
When selecting and moving many elements, the performance breaks down. The selection of many elements could be sped up massively by drawing single selection boxes (instead of merging them to a single selection area like it is now) or just one selection rectangle.

**Comment by ggonnella** [comment]
> The selection of many elements could be sped up massively by drawing single selection boxes (instead of merging them to a single selection area like it is now) or just one selection rectangle.

It's a pity, as the current selection highlighting is very nice. Maybe change it just for large graphs (i.e. over a certain number of elements)? Or this could be tricky?

**Comment by ggonnella** [comment]
Fixed.
