### ISSUE TITLE
Node length with the FMMM Layout

### ISSUE THREAD

**Issue by ggonnella** [niehus/gfaviz#44]
We mentioned today in the meeting, that the node length with one of the two layouts is not implemented completely. If I remember this is the FMMM layout? We have to find a way to fix this.

**Comment by holtsetio** [comment]
This patch results in the fmmm-Layout using the edgeLengths-array. Default Edgelengths could still use some tweaking I guess. Also the fmmm-Layout follows the EdgeLengths more strictly than SM does with the weights, so internal-edges tend to break the layout more often.
[fmmm-patch.txt](https://github.com/niehus/gfaviz/files/2358017/fmmm-patch.txt)

**Comment by ggonnella** [comment]
Patch is applied, but I think it's not working

**Comment by ggonnella** [comment]
Probably the changes I made in the patch does not make it work.
(to check: line setting length)

**Comment by ggonnella** [comment]
Introduced layout specific multipliers to fix this.
