### ISSUE TITLE
Clipped long tags in Graph info

### ISSUE THREAD

**Issue by ggonnella** [niehus/gfaviz#6]
![screenshot_20180828_113649](https://user-images.githubusercontent.com/21620/44714975-e6568600-aab6-11e8-829a-0d5b2fa7d226.png)

If a tag contains a long text, it is not possible to see its content.

Possible solutions to consider:
- allow to resize the right column of the table, so that the user can scroll to the right and see the rest.
- mouseover with the entire content in a tooltip

**Comment by holtsetio** [comment]
Added tooltips in 731af1ddda197dfe73c5139653852b047f2467fe.
