### ISSUE TITLE
Resizable Graph Info/ Current Selection

### ISSUE THREAD

**Issue by ggonnella** [niehus/gfaviz#7]
![screenshot_20180828_114317](https://user-images.githubusercontent.com/21620/44715259-9deb9800-aab7-11e8-8259-9e31237c7bf2.png)

Sometimes there is a lot of information in Graph info and nothing in Current Selection. It would be nice to be able to resize graph info at the expenses of current selection by dragging the bar separating them.

**Comment by holtsetio** [comment]
Implemented in 8b984793ddab90cb8ef7f6df3751560b26d3f8b6.
