### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by ikyih** [niehus/gfaviz#74]
i cant build it. please make a build

**Comment by mictadlo** [comment]
I have the same problem on a Mac with Apple Silicon:
```
$  wget -c https://github.com/ggonnella/gfaviz/archive/refs/tags/v1.0.0.tar.gz
$ ar xfvz v1.0.0.tar.gz
$ cd gfaviz-1.0.0
$ qmake-qt5 NOSVG=true
zsh: command not found: qmake-qt5
```

**Comment by ikyih** [comment]
i dont actually need this anymore

**Comment by smriti-135** [comment]
> I have the same problem on a Mac with Apple Silicon:
 ``` zsh: command not found: qmake-qt5```

Did you get it solved @mictadlo
