### ISSUE TITLE
Compatibility with rGFA?

### ISSUE THREAD

**Issue by yjx1217** [niehus/gfaviz#76]
Hello,

I was wondering if gfaviz is compatible with the rGFA format? 
There seems no information available online regarding this. 
Thanks in advance!

Best,
Jia-Xing

**Comment by ggonnella** [comment]
Hi Jia Xing,

at the time we wrote the software, rGFA did not exist yet. At the moment
there is not a clear plan to upgrade it to include the special features of
rGFA. However rGFA is also compatible in most parts with GFA1, so you
might try to load the files.

Best regards
Giorgio

**Comment by yjx1217** [comment]
Hi Giorgio,

Many thanks for the blazing fast reply! :-)

Best,
Jia-Xing
