### ISSUE TITLE
Tag Datatype

### ISSUE THREAD

**Issue by ggonnella** [niehus/gfaviz#8]
![screenshot_20180828_113649](https://user-images.githubusercontent.com/21620/44715333-d25f5400-aab7-11e8-8983-c1ee119d6fe7.png)

The datatype of the tags is not visualized.
Maybe it could be just added in parenthesis after the tag name.

e.g.
tags
|--- vo (Z)        {"label-color"...

**Comment by holtsetio** [comment]
Added in 731af1ddda197dfe73c5139653852b047f2467fe.
