### ISSUE TITLE
Label and element movement

### ISSUE THREAD

**Issue by ggonnella** [niehus/gfaviz#9]
If I remember well, the movement of a label previously worked when the user went on the label itself.
This was connected with issues and was changed (how?).

However something is not working currently, after selecting a group of elements. In fact, if one clicks and drags from the element, the entire selection moves (correctly). If the user clicks on the label and drags, then the selection is lost and the single element is moved (not its label anyway). This is unexpected.

I think the different behavior when clicking on the label should be avoided.
To move the label, one could maybe use a Shift or Ctrl modifier to the drag if supported by Qt.

**Comment by ggonnella** [comment]
Note: the label movement for gaps, groups and edges works correctly. The issue only affects segments.

**Comment by holtsetio** [comment]
Implemented in 731af1ddda197dfe73c5139653852b047f2467fe. Labels can now be moved when the Shift-key is pressed (and only then). Also the label position can be saved in the gfa file now.
